name: Publish to GH Pages

on:
  push:
    branches:
      - 'master'

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: "Cache dependencies"
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}build-node-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-build-node-

    - name: "Install dependencies"
      run: yarn install --frozen-lockfile

    - name: "Build"
      run: yarn build

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
        cname: what-the-semver.efrane.com
